# Generated by Django 4.1.7 on 2023-05-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Multipliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multi_0_50", models.IntegerField()),
                ("multi_51_150", models.IntegerField()),
                ("multi_151_700", models.IntegerField()),
                ("multi_701_1500", models.IntegerField()),
                ("multi_1501_3000", models.IntegerField()),
                ("multi_3001_6000", models.IntegerField()),
                ("multi_6001_8", models.IntegerField()),
            ],
        ),
    ]
