# Generated by Django 4.1.7 on 2023-05-12 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_description_product_min_qty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("historic", "0002_remove_historic_description_historic_applicant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historic",
            name="createdBy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="historic",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
