# Generated by Django 4.1.7 on 2023-03-17 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("entry_cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("final_cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("qty", models.IntegerField()),
                ("image", models.ImageField(max_length=30, null=True, upload_to="")),
            ],
        ),
    ]
