# Generated by Django 4.1.7 on 2023-03-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="final_cost",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
