# Generated by Django 4.1.7 on 2023-04-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("products", "0002_alter_product_final_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="groups.group",
            ),
        ),
    ]
