# Generated by Django 4.1.7 on 2023-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.IntegerField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
