# Generated by Django 4.1.7 on 2023-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_code_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.IntegerField(editable=False),
        ),
    ]
