# Generated by Django 4.1.7 on 2023-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_qty",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
