# Generated by Django 4.1.7 on 2023-05-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_description_product_min_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="final_cost_altered",
            field=models.BooleanField(default=False),
        ),
    ]
